spring:
  data:
    mongodb:
      username: rootuser
      password: rootpass
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: customer-events

server:
  port: 8090