spring:
  data:
    mongodb:
      username: rootuser
      password: rootpass
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090