spring:
  config:
    import: optional:configserver:http://config-service:8888
  application:
    name: gateway-service


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"