services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    volumes:
      - mongo:/data
    networks:
      - backend

  postgresql:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: postuser
      POSTGRES_PASSWORD: postpass
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

  mail-dev:
    container_name: ms_mailing
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1  # Unique ID for the broker
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # ZooKeeper connection
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092  # Simplified to one listener for single broker
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092  # Advertised to host
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT  # Security protocol
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT  # Inter-broker listener (single broker case)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # Single broker, so replication factor is 1
      KAFKA_NUM_PARTITIONS: 8  # Default number of partitions for new topics
      KAFKA_LOG_DIRS: /var/lib/kafka/data  # Log directory
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"  # Disable Confluent metrics
    #    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
##      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mongo:
  postgres:

networks:
  backend:
    driver: bridge