spring:
  config:
    import: optional:localhost:http://config-service:8888
  application:
    name: discovery-service

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"